### ISSUE TITLE
Exploit: Can "save" drop damage protection for later use by landing in water.

### ISSUE THREAD

**Issue by zedwick** [MLG-Fortress/PopulationDensity#17]
If a player is dropped when travelling to a region post and lands in water, their protection from fall damage will not be activated and will instead protect them from the next fall damage they would receive.

For example, they could /visit a region post, fall into water and then walk to a nearby deep pit and jump down to bedrock without taking damage.

**Comment by RoboMWM** [comment]
Yup. There's some ways to deal with this.

1. A scheduled task that removes the falldamage metdata/hash entry after ~30 seconds.
2. A repeated task that removes when onGround is true (not sure if this is true when a player is in water?)
3. Like number 2, but using playermoveevent instead of a repeating task.

**Comment by zedwick** [comment]
I would think just checking for onGround would be good enough; pretty sure it's not set when in water, but It'd be very difficult to transition from water to falling without either falling through it or going down a water fall. Both of those I think we can consider to be still falling/not exploitable.
