### ISSUE TITLE
Respawn after death kills new players

### ISSUE THREAD

**Issue by JethroHotep** [MLG-Fortress/PopulationDensity#44]
If a player has not set a bed and dies, they are dropped on the region post and die again from fall damage.

Potentially relevant settings:
  NewPlayersSpawnInHomeRegion: true
  RespawnInHomeRegion: true
  LaunchAndDropPlayers: true
  LaunchAndDropNewPlayers: true
  PreciseWorldSpawn: true

I have turned launch and drop off for now, but would really like to be able to turn it back on.

**Comment by RoboMWM** [comment]
> they are dropped on the region post and die again from fall damage.

This shouldn't be happening, since they should have fall damage immunity at this time. Something is resetting this attribute (double damage)?

**Comment by JethroHotep** [comment]
And the beer gets lumpy.  Found the problem, and it is not in the plugin...  So, respawn Y is set like this:
 
```
homeRegionCenter.setY(PopulationDensity.ManagedWorld
					.getHighestBlockYAt(homeRegionCenter) + 2);
```

That is a nice simple solution for setting a Y for the top of the region post.  Unfortunately, Y is coming back as the highest block that existed before a WorldEdit cut.  So, even though there is nothing but air over the post, at one time there was a huge statue there that I "cut" with WorldEdit.  For some reason, Spigot is returning the top of that statue as the Highest Y.  Since the statue is actually gone, ahhhhhhh.... splat. I manually built a column above the post and broke it, and now Spigot knows there is nothing but air there. Happy days, no more screaming falling death loops. It was all a WorldEdit artifact.

Thanks for responding so quickly.

**Comment by RoboMWM** [comment]
Ah ok. I kinda recalled that respawns shouldn't drop players in, but wasn't sure.

`getHighestBlock` and `getHighestBlockYAt` use light afaik to determine what the highest block is. This is why stuff like glass aren't reported as the highest block. So in this case, WorldEdit didn't update the lighting (though I'm going to assume that this is because of FAWE/AWE since they skip the bukkit API and place blocks directly via NMS, thus not triggering relighting).
