### ISSUE TITLE
Error on Item Despawn (v5.11.beta)

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/PopulationDensity#56]
This keeps being spammed.

https://hastebin.com/efadikarof.cs

**Comment by ghost** [comment]
@RoboMWM can you have a look at this? This is spammed all over the console.

**Comment by RoboMWM** [comment]
Sorry I saw it but didn't have time to look at since was on phone, and then forgot. From what I recall though the line that's supposedly indicates a change in spigot's API on that getBlock call.

**Comment by RoboMWM** [comment]
Sorry I saw it but didn't have time to look at since was on phone, and then forgot.

**Comment by RoboMWM** [comment]
Yup, was a screw up in PR #48 https://github.com/TechFortress/PopulationDensity/commit/128baeb821cc51a3205b51bb0390b0bb5858af7b#diff-de96e76af3de99fe21a9802005b443abR134

Logical error, boolean logic should be inverted. This is also why we make separate PRs per change instead of lumping a ton of changes together c:
