### ISSUE TITLE
Worlds with empty chunks cause region scanning to hang

### ISSUE THREAD

**Issue by ArZorMC** [MLG-Fortress/PopulationDensity#57]
I'm trying to use this on a custom generated world and on 1st startup with the initial scan i get this massive console spam and it ends up crashing the server:
https://pastebin.com/y9Mrj35X

**Comment by ghost** [comment]
The 1.13 versions seriously need to be tested more. :/

**Comment by RoboMWM** [comment]
It only calls sleep if the snapshot returned was filled with air. Which, considering how slow 1.13 currently is, is not much of a surprise. Try pre-generating your world first. If your custom-generated world has a lot of empty space though... then that would be why.

(An aside - if we were to use the Paper API, we could make the entire scanning process asynchronous since it's possible to load chunks asynchronously in Paper).

**Comment by RoboMWM** [comment]
Closed in 08d38c1b4d4832c95176535a3b61d41034174b01 since sleeping the thread doesn't make sense there anyways. However before I link you to the build I'm curious to know if your custom world has holes in it..?

**Comment by ArZorMC** [comment]
If by holes you mean areas that have a break in the bedrock so a player could fall into the void then that would only occur outside the world border.

**Comment by RoboMWM** [comment]
holes as in all air blocks from y=0-255. Gonna guess that your pregenerated world is surrounded with pregenerated empty void space (air pockets/air block from 0-255) then...?

**Comment by ArZorMC** [comment]
That is correct, there is void surrounding my custom map, however i don't know if it makes a difference that i used worldedit to create the void rather than a void world generator. So there is land about 500 blocks out from the void in each cardinal direction.

**Comment by RoboMWM** [comment]
Ok just wanted to make sure, thanks.

**Comment by RoboMWM** [comment]
Fixed in 5.11.1
