### ISSUE TITLE
command to show coordinates of the nearest pole

### ISSUE THREAD

**Issue by JavierPM87** [MLG-Fortress/PopulationDensity#96]
Hello, I was on a server, when writing a command, it showed you the coordinates of the post closest to you, now I have set up my own server and I do not see the option or the command for it, how can this be configured?

**Comment by RoboMWM** [comment]
Very likely an addon did that? Don't think this plugin ever provided that, but its API is very easy to get at to get such data.

**Comment by JavierPM87** [comment]
Thank you very much for the information, I will talk with a friend to see if he can help me

**Comment by JavierPM87** [comment]
You could add that option to your plugin, this helps users find the closest post to your position ;)

**Comment by JavierPM87** [comment]
it is probably in RegionCoordinates.java, but I have no idea how to use it :(

**Comment by RoboMWM** [comment]
I don't see a benefit to adding it to the main plugin. Yes I know some people like coordinates but the idea behind posts are moreso for people to build around them, and to be identified by name. Perhaps I'll accept a PR if someone adds it in with a permission (that defaults to op or false), but otherwise I don't really see how it fits with the plugin's design.
