### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by pilahito** [MLG-Fortress/PopulationDensity#99]
Yo, can u update the plugin? i've a lot of errors with the plugin and their perfomance. 

U can see it here: https://timings.pl3x.net/?id=b474a2aa4c4546c1a12bdf763e8cb5bb
Thanks!

**Comment by zedwick** [comment]
A new ticket per complaint, please.

Please provide your logs with the errors you are seeing.

I admit I'm not very good at reading timings, but to me it looks like Population Density's scan region task is shown to take a long time because it is waiting for chunks to load. I believe you can change the length of time between scans, or disable them from running on a schedule entirely, in the config if you find they are a problem for you.

**Comment by RoboMWM** [comment]
timings are not equal to errors.

That is a very short timings report, and that is definitely due to chunks taking forever to load. Also, there are things you can do on your end to improve performance such as using aikar's flags since your current flags are actually very bad and _will_ cause a lot of gc to occur before it grows to your max size.
